### PR TITLE
Update assets.json

### PR DESCRIPTION
**Pull request by forskvll**

### CODE REVIEW

**Comment by grandsmarquis** [comment]
Hey not sure what LP token you added as it looks like to be for Pineapple something

**Comment by forskvll** [comment]
Hi let me check again pls

**Comment by forskvll** [comment]
0x2339dabd4bf681196ccb676cabb12010d97c26ce

This is the LP token how do i edit? Sorry never done this before!

**Comment by forskvll** [comment]
> Hey not sure what LP token you added as it looks like to be for Pineapple something

Is it good now?

**Comment by surfer77** [comment]
It's perfect, thank you

**Comment by forskvll** [comment]
> It's perfect, thank you

Any help why there is no buy or sell button? Positive i added liquidity in there

**Pull request merged**
