### PR TITLE
Update assets.json

### PR DESCRIPTION
**Pull request by FermiGBM**
Three Dragons pool info and logo.

### CODE REVIEW

**Review by grandsmarquis — COMMENTED** [review]
Thanks!

**Review by grandsmarquis — COMMENTED** [review]
Did you create the pool yet using https://nft20.io/create ?

**Comment by FermiGBM** [comment]
> Did you create the pool yet using https://nft20.io/create ?
Yes we've submitted the pool transaction here: https://polygonscan.com/tx/0xc1d464c661b9da9153a5104839d694f100f1457446c3b254b32ed30f5abcc840

**Comment by grandsmarquis** [comment]
Ah okay this is on Polygon you need to add it here: https://github.com/verynifty/nft20-assets/blob/master/assets_matic.json

**Comment by grandsmarquis** [comment]
But NFT20 on Polygon is currently paused as we are building a service to index data there: 
https://twitter.com/NiftyMuseum/status/1457413233678114818

**Pull request merged**
